<?php

namespace App\Http\Controllers\HR\ATS;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Inertia\Inertia;
use Inertia\Response;

class HiringPipelineController extends Controller
{
    /**
     * Display the hiring pipeline (Kanban + list view).
     */
    public function index(Request $request): Response
    {
        // Mock data: Applications grouped by status
        $applications = [
            // Submitted applications
            [
                'id' => 1,
                'candidate_id' => 1,
                'candidate_name' => 'John Doe',
                'job_id' => 1,
                'job_title' => 'Senior Software Engineer',
                'status' => 'submitted',
                'applied_at' => '2025-11-01',
                'candidate_source' => 'job_board',
                'candidate_email' => 'john.doe@example.com',
                'candidate_phone' => '+1234567890',
            ],
            [
                'id' => 2,
                'candidate_id' => 2,
                'candidate_name' => 'Michael Brown',
                'job_id' => 1,
                'job_title' => 'Senior Software Engineer',
                'status' => 'submitted',
                'applied_at' => '2025-11-02',
                'candidate_source' => 'referral',
                'candidate_email' => 'michael.brown@example.com',
                'candidate_phone' => '+1234567891',
            ],
            [
                'id' => 3,
                'candidate_id' => 3,
                'candidate_name' => 'Jane Smith',
                'job_id' => 2,
                'job_title' => 'Marketing Manager',
                'status' => 'submitted',
                'applied_at' => '2025-11-03',
                'candidate_source' => 'facebook',
                'candidate_email' => 'jane.smith@example.com',
                'candidate_phone' => '+1234567892',
            ],
            [
                'id' => 4,
                'candidate_id' => 4,
                'candidate_name' => 'Emily Johnson',
                'job_id' => 3,
                'job_title' => 'Financial Analyst',
                'status' => 'submitted',
                'applied_at' => '2025-11-04',
                'candidate_source' => 'walk_in',
                'candidate_email' => 'emily.johnson@example.com',
                'candidate_phone' => '+1234567893',
            ],
            [
                'id' => 5,
                'candidate_id' => 5,
                'candidate_name' => 'Robert Martinez',
                'job_id' => 3,
                'job_title' => 'Financial Analyst',
                'status' => 'submitted',
                'applied_at' => '2025-11-05',
                'candidate_source' => 'agency',
                'candidate_email' => 'robert.martinez@example.com',
                'candidate_phone' => '+1234567894',
            ],
            [
                'id' => 6,
                'candidate_id' => 6,
                'candidate_name' => 'Sarah Williams',
                'job_id' => 4,
                'job_title' => 'HR Coordinator',
                'status' => 'submitted',
                'applied_at' => '2025-11-06',
                'candidate_source' => 'job_board',
                'candidate_email' => 'sarah.williams@example.com',
                'candidate_phone' => '+1234567895',
            ],
            [
                'id' => 7,
                'candidate_id' => 7,
                'candidate_name' => 'Lisa Anderson',
                'job_id' => 4,
                'job_title' => 'HR Coordinator',
                'status' => 'submitted',
                'applied_at' => '2025-11-07',
                'candidate_source' => 'referral',
                'email' => 'lisa.anderson@example.com',
                'phone' => '+1234567896',
            ],
            [
                'id' => 8,
                'candidate_id' => 8,
                'candidate_name' => 'Patricia Garcia',
                'job_posting_id' => 5,
                'job_title' => 'Customer Service Representative',
                'status' => 'submitted',
                'applied_date' => '2025-11-08',
                'source' => 'walk_in',
                'email' => 'patricia.garcia@example.com',
                'phone' => '+1234567897',
            ],
            [
                'id' => 9,
                'candidate_id' => 9,
                'candidate_name' => 'James Taylor',
                'job_posting_id' => 1,
                'job_title' => 'Senior Software Engineer',
                'status' => 'submitted',
                'applied_date' => '2025-11-09',
                'source' => 'job_board',
                'email' => 'james.taylor@example.com',
                'phone' => '+1234567898',
            ],
            [
                'id' => 10,
                'candidate_id' => 10,
                'candidate_name' => 'Christopher Lee',
                'job_posting_id' => 6,
                'job_title' => 'Project Manager',
                'status' => 'submitted',
                'applied_date' => '2025-11-10',
                'source' => 'internal',
                'email' => 'christopher.lee@example.com',
                'phone' => '+1234567899',
            ],
            [
                'id' => 11,
                'candidate_id' => 11,
                'candidate_name' => 'David Harris',
                'job_posting_id' => 2,
                'job_title' => 'Marketing Manager',
                'status' => 'submitted',
                'applied_date' => '2025-11-11',
                'source' => 'facebook',
                'email' => 'david.harris@example.com',
                'phone' => '+1234567800',
            ],
            [
                'id' => 12,
                'candidate_id' => 12,
                'candidate_name' => 'Amanda White',
                'job_posting_id' => 2,
                'job_title' => 'Marketing Manager',
                'status' => 'submitted',
                'applied_date' => '2025-11-11',
                'source' => 'agency',
                'email' => 'amanda.white@example.com',
                'phone' => '+1234567801',
            ],

            // Shortlisted applications
            [
                'id' => 13,
                'candidate_id' => 13,
                'candidate_name' => 'Daniel Clark',
                'job_posting_id' => 1,
                'job_title' => 'Senior Software Engineer',
                'status' => 'shortlisted',
                'applied_date' => '2025-10-28',
                'source' => 'referral',
                'email' => 'daniel.clark@example.com',
                'phone' => '+1234567802',
            ],
            [
                'id' => 14,
                'candidate_id' => 14,
                'candidate_name' => 'Jennifer Lewis',
                'job_posting_id' => 3,
                'job_title' => 'Financial Analyst',
                'status' => 'shortlisted',
                'applied_date' => '2025-10-29',
                'source' => 'job_board',
                'email' => 'jennifer.lewis@example.com',
                'phone' => '+1234567803',
            ],
            [
                'id' => 15,
                'candidate_id' => 15,
                'candidate_name' => 'Daniel Thomas',
                'job_posting_id' => 3,
                'job_title' => 'Financial Analyst',
                'status' => 'shortlisted',
                'applied_date' => '2025-10-30',
                'source' => 'walk_in',
                'email' => 'daniel.thomas@example.com',
                'phone' => '+1234567804',
            ],
            [
                'id' => 16,
                'candidate_id' => 16,
                'candidate_name' => 'Matthew Walker',
                'job_posting_id' => 4,
                'job_title' => 'HR Coordinator',
                'status' => 'shortlisted',
                'applied_date' => '2025-10-31',
                'source' => 'referral',
                'email' => 'matthew.walker@example.com',
                'phone' => '+1234567805',
            ],
            [
                'id' => 17,
                'candidate_id' => 17,
                'candidate_name' => 'Nancy Hall',
                'job_posting_id' => 2,
                'job_title' => 'Marketing Manager',
                'status' => 'shortlisted',
                'applied_date' => '2025-11-01',
                'source' => 'facebook',
                'email' => 'nancy.hall@example.com',
                'phone' => '+1234567806',
            ],
            [
                'id' => 18,
                'candidate_id' => 18,
                'candidate_name' => 'Jessica Martinez',
                'job_posting_id' => 7,
                'job_title' => 'Data Analyst',
                'status' => 'shortlisted',
                'applied_date' => '2025-11-02',
                'source' => 'job_board',
                'email' => 'jessica.martinez@example.com',
                'phone' => '+1234567807',
            ],
            [
                'id' => 19,
                'candidate_id' => 19,
                'candidate_name' => 'Paul Allen',
                'job_posting_id' => 6,
                'job_title' => 'Project Manager',
                'status' => 'shortlisted',
                'applied_date' => '2025-11-03',
                'source' => 'internal',
                'email' => 'paul.allen@example.com',
                'phone' => '+1234567808',
            ],
            [
                'id' => 20,
                'candidate_id' => 20,
                'candidate_name' => 'David Rodriguez',
                'job_posting_id' => 8,
                'job_title' => 'Sales Executive',
                'status' => 'shortlisted',
                'applied_date' => '2025-11-04',
                'source' => 'agency',
                'email' => 'david.rodriguez@example.com',
                'phone' => '+1234567809',
            ],

            // Interviewed applications
            [
                'id' => 21,
                'candidate_id' => 21,
                'candidate_name' => 'Sandra Young',
                'job_posting_id' => 1,
                'job_title' => 'Senior Software Engineer',
                'status' => 'interviewed',
                'applied_date' => '2025-10-20',
                'source' => 'referral',
                'email' => 'sandra.young@example.com',
                'phone' => '+1234567810',
                'interview_date' => '2025-11-08',
                'interview_score' => 8,
            ],
            [
                'id' => 22,
                'candidate_id' => 22,
                'candidate_name' => 'Sarah Johnson',
                'job_posting_id' => 4,
                'job_title' => 'HR Coordinator',
                'status' => 'interviewed',
                'applied_date' => '2025-10-22',
                'source' => 'job_board',
                'email' => 'sarah.j@example.com',
                'phone' => '+1234567811',
                'interview_date' => '2025-11-09',
                'interview_score' => 7,
            ],
            [
                'id' => 23,
                'candidate_id' => 23,
                'candidate_name' => 'Kenneth King',
                'job_posting_id' => 2,
                'job_title' => 'Marketing Manager',
                'status' => 'interviewed',
                'applied_date' => '2025-10-23',
                'source' => 'facebook',
                'email' => 'kenneth.king@example.com',
                'phone' => '+1234567812',
                'interview_date' => '2025-11-10',
                'interview_score' => 9,
            ],
            [
                'id' => 24,
                'candidate_id' => 24,
                'candidate_name' => 'Karen Wright',
                'job_posting_id' => 6,
                'job_title' => 'Project Manager',
                'status' => 'interviewed',
                'applied_date' => '2025-10-24',
                'source' => 'internal',
                'email' => 'karen.wright@example.com',
                'phone' => '+1234567813',
                'interview_date' => '2025-11-06',
                'interview_score' => 8,
            ],
            [
                'id' => 25,
                'candidate_id' => 25,
                'candidate_name' => 'Kevin Brown',
                'job_posting_id' => 9,
                'job_title' => 'Operations Manager',
                'status' => 'interviewed',
                'applied_date' => '2025-10-25',
                'source' => 'agency',
                'email' => 'kevin.brown@example.com',
                'phone' => '+1234567814',
                'interview_date' => '2025-11-07',
                'interview_score' => 7,
            ],

            // Offered applications
            [
                'id' => 26,
                'candidate_id' => 26,
                'candidate_name' => 'Barbara Lopez',
                'job_posting_id' => 1,
                'job_title' => 'Senior Software Engineer',
                'status' => 'offered',
                'applied_date' => '2025-10-15',
                'source' => 'referral',
                'email' => 'barbara.lopez@example.com',
                'phone' => '+1234567815',
                'interview_date' => '2025-10-30',
                'interview_score' => 9,
                'offer_date' => '2025-11-05',
            ],
            [
                'id' => 27,
                'candidate_id' => 27,
                'candidate_name' => 'Steven Hill',
                'job_posting_id' => 2,
                'job_title' => 'Marketing Manager',
                'status' => 'offered',
                'applied_date' => '2025-10-16',
                'source' => 'facebook',
                'email' => 'steven.hill@example.com',
                'phone' => '+1234567816',
                'interview_date' => '2025-10-31',
                'interview_score' => 8,
                'offer_date' => '2025-11-06',
            ],

            // Hired applications
            [
                'id' => 28,
                'candidate_id' => 28,
                'candidate_name' => 'Michelle Davis',
                'job_posting_id' => 5,
                'job_title' => 'Customer Service Representative',
                'status' => 'hired',
                'applied_date' => '2025-10-01',
                'source' => 'walk_in',
                'email' => 'michelle.davis@example.com',
                'phone' => '+1234567817',
                'interview_date' => '2025-10-20',
                'interview_score' => 8,
                'offer_date' => '2025-10-25',
                'hire_date' => '2025-11-01',
            ],
            [
                'id' => 29,
                'candidate_id' => 29,
                'candidate_name' => 'Ryan Scott',
                'job_posting_id' => 3,
                'job_title' => 'Financial Analyst',
                'status' => 'hired',
                'applied_date' => '2025-09-28',
                'source' => 'job_board',
                'email' => 'ryan.scott@example.com',
                'phone' => '+1234567818',
                'interview_date' => '2025-10-18',
                'interview_score' => 9,
                'offer_date' => '2025-10-23',
                'hire_date' => '2025-11-01',
            ],
            [
                'id' => 30,
                'candidate_id' => 30,
                'candidate_name' => 'Brian Wilson',
                'job_posting_id' => 6,
                'job_title' => 'Project Manager',
                'status' => 'hired',
                'applied_date' => '2025-09-25',
                'source' => 'internal',
                'email' => 'brian.wilson@example.com',
                'phone' => '+1234567819',
                'interview_date' => '2025-10-15',
                'interview_score' => 8,
                'offer_date' => '2025-10-20',
                'hire_date' => '2025-10-28',
            ],

            // Rejected applications
            [
                'id' => 31,
                'candidate_id' => 31,
                'candidate_name' => 'Laura Green',
                'job_posting_id' => 1,
                'job_title' => 'Senior Software Engineer',
                'status' => 'rejected',
                'applied_date' => '2025-10-10',
                'source' => 'job_board',
                'email' => 'laura.green@example.com',
                'phone' => '+1234567820',
                'rejection_reason' => 'Insufficient experience',
            ],
            [
                'id' => 32,
                'candidate_id' => 32,
                'candidate_name' => 'Jason Adams',
                'job_posting_id' => 2,
                'job_title' => 'Marketing Manager',
                'status' => 'rejected',
                'applied_date' => '2025-10-11',
                'source' => 'facebook',
                'email' => 'jason.adams@example.com',
                'phone' => '+1234567821',
                'rejection_reason' => 'Better candidates selected',
            ],
            [
                'id' => 33,
                'candidate_id' => 33,
                'candidate_name' => 'Rebecca Baker',
                'job_posting_id' => 3,
                'job_title' => 'Financial Analyst',
                'status' => 'rejected',
                'applied_date' => '2025-10-12',
                'source' => 'agency',
                'email' => 'rebecca.baker@example.com',
                'phone' => '+1234567822',
                'rejection_reason' => 'Lack of required certifications',
            ],
            [
                'id' => 34,
                'candidate_id' => 34,
                'candidate_name' => 'Gregory Nelson',
                'job_posting_id' => 4,
                'job_title' => 'HR Coordinator',
                'status' => 'rejected',
                'applied_date' => '2025-10-13',
                'source' => 'walk_in',
                'email' => 'gregory.nelson@example.com',
                'phone' => '+1234567823',
                'rejection_reason' => 'Poor cultural fit',
            ],
            [
                'id' => 35,
                'candidate_id' => 35,
                'candidate_name' => 'Stephanie Carter',
                'job_posting_id' => 8,
                'job_title' => 'Sales Executive',
                'status' => 'rejected',
                'applied_date' => '2025-10-14',
                'source' => 'job_board',
                'email' => 'stephanie.carter@example.com',
                'phone' => '+1234567824',
                'interview_date' => '2025-10-28',
                'interview_score' => 5,
                'rejection_reason' => 'Low interview score',
            ],
            [
                'id' => 36,
                'candidate_id' => 36,
                'candidate_name' => 'Timothy Mitchell',
                'job_posting_id' => 5,
                'job_title' => 'Customer Service Representative',
                'status' => 'rejected',
                'applied_date' => '2025-10-15',
                'source' => 'walk_in',
                'email' => 'timothy.mitchell@example.com',
                'phone' => '+1234567825',
                'rejection_reason' => 'Communication skills below requirements',
            ],
            [
                'id' => 37,
                'candidate_id' => 37,
                'candidate_name' => 'Nicole Perez',
                'job_posting_id' => 7,
                'job_title' => 'Data Analyst',
                'status' => 'rejected',
                'applied_date' => '2025-10-16',
                'source' => 'job_board',
                'email' => 'nicole.perez@example.com',
                'phone' => '+1234567826',
                'rejection_reason' => 'No experience with required tools',
            ],
            [
                'id' => 38,
                'candidate_id' => 38,
                'candidate_name' => 'Brandon Roberts',
                'job_posting_id' => 6,
                'job_title' => 'Project Manager',
                'status' => 'rejected',
                'applied_date' => '2025-10-17',
                'source' => 'agency',
                'email' => 'brandon.roberts@example.com',
                'phone' => '+1234567827',
                'interview_date' => '2025-10-29',
                'interview_score' => 6,
                'rejection_reason' => 'Insufficient project management experience',
            ],
            [
                'id' => 39,
                'candidate_id' => 39,
                'candidate_name' => 'Melissa Turner',
                'job_posting_id' => 1,
                'job_title' => 'Senior Software Engineer',
                'status' => 'rejected',
                'applied_date' => '2025-10-18',
                'source' => 'referral',
                'email' => 'melissa.turner@example.com',
                'phone' => '+1234567828',
                'rejection_reason' => 'Position already filled',
            ],
            [
                'id' => 40,
                'candidate_id' => 40,
                'candidate_name' => 'Samuel Phillips',
                'job_posting_id' => 9,
                'job_title' => 'Operations Manager',
                'status' => 'rejected',
                'applied_date' => '2025-10-19',
                'source' => 'job_board',
                'email' => 'samuel.phillips@example.com',
                'phone' => '+1234567829',
                'interview_date' => '2025-11-01',
                'interview_score' => 5,
                'rejection_reason' => 'Weak leadership skills',
            ],
            [
                'id' => 41,
                'candidate_id' => 41,
                'candidate_name' => 'Rachel Campbell',
                'job_posting_id' => 2,
                'job_title' => 'Marketing Manager',
                'status' => 'rejected',
                'applied_date' => '2025-10-20',
                'source' => 'facebook',
                'email' => 'rachel.campbell@example.com',
                'phone' => '+1234567830',
                'rejection_reason' => 'Overqualified',
            ],
            [
                'id' => 42,
                'candidate_id' => 42,
                'candidate_name' => 'Eric Parker',
                'job_posting_id' => 3,
                'job_title' => 'Financial Analyst',
                'status' => 'rejected',
                'applied_date' => '2025-10-21',
                'source' => 'walk_in',
                'email' => 'eric.parker@example.com',
                'phone' => '+1234567831',
                'rejection_reason' => 'Incomplete application',
            ],
            [
                'id' => 43,
                'candidate_id' => 43,
                'candidate_name' => 'Carolyn Evans',
                'job_posting_id' => 4,
                'job_title' => 'HR Coordinator',
                'status' => 'rejected',
                'applied_date' => '2025-10-22',
                'source' => 'agency',
                'email' => 'carolyn.evans@example.com',
                'phone' => '+1234567832',
                'rejection_reason' => 'Salary expectations too high',
            ],
            [
                'id' => 44,
                'candidate_id' => 44,
                'candidate_name' => 'Patrick Edwards',
                'job_posting_id' => 8,
                'job_title' => 'Sales Executive',
                'status' => 'rejected',
                'applied_date' => '2025-10-23',
                'source' => 'job_board',
                'email' => 'patrick.edwards@example.com',
                'phone' => '+1234567833',
                'interview_date' => '2025-11-02',
                'interview_score' => 4,
                'rejection_reason' => 'Did not meet sales targets in previous role',
            ],
            [
                'id' => 45,
                'candidate_id' => 45,
                'candidate_name' => 'Angela Collins',
                'job_posting_id' => 7,
                'job_title' => 'Data Analyst',
                'status' => 'rejected',
                'applied_date' => '2025-10-24',
                'source' => 'referral',
                'email' => 'angela.collins@example.com',
                'phone' => '+1234567834',
                'rejection_reason' => 'No statistical analysis experience',
            ],
        ];

        // Normalize all applications to have consistent field names
        $applications = array_map(function($app) {
            return [
                'id' => $app['id'],
                'candidate_id' => $app['candidate_id'],
                'candidate_name' => $app['candidate_name'],
                'job_id' => $app['job_id'] ?? $app['job_posting_id'] ?? null,
                'job_title' => $app['job_title'],
                'status' => $app['status'],
                'applied_at' => $app['applied_at'] ?? $app['applied_date'] ?? null,
                'candidate_email' => $app['candidate_email'] ?? $app['email'] ?? null,
                'candidate_phone' => $app['candidate_phone'] ?? $app['phone'] ?? null,
                'candidate_source' => $app['candidate_source'] ?? $app['source'] ?? 'other',
            ];
        }, $applications);

        // Add candidate property with source for filtering
        $applications = array_map(function($app) {
            $app['candidate'] = [
                'id' => $app['candidate_id'],
                'name' => $app['candidate_name'],
                'source' => $app['candidate_source'],
            ];
            return $app;
        }, $applications);

        // Group applications by status for pipeline
        $pipeline = [
            [
                'status' => 'submitted',
                'label' => 'Submitted',
                'count' => count(array_filter($applications, fn($a) => $a['status'] === 'submitted')),
                'applications' => array_values(array_filter($applications, fn($a) => $a['status'] === 'submitted')),
            ],
            [
                'status' => 'shortlisted',
                'label' => 'Shortlisted',
                'count' => count(array_filter($applications, fn($a) => $a['status'] === 'shortlisted')),
                'applications' => array_values(array_filter($applications, fn($a) => $a['status'] === 'shortlisted')),
            ],
            [
                'status' => 'interviewed',
                'label' => 'Interviewed',
                'count' => count(array_filter($applications, fn($a) => $a['status'] === 'interviewed')),
                'applications' => array_values(array_filter($applications, fn($a) => $a['status'] === 'interviewed')),
            ],
            [
                'status' => 'offered',
                'label' => 'Offered',
                'count' => count(array_filter($applications, fn($a) => $a['status'] === 'offered')),
                'applications' => array_values(array_filter($applications, fn($a) => $a['status'] === 'offered')),
            ],
            [
                'status' => 'hired',
                'label' => 'Hired',
                'count' => count(array_filter($applications, fn($a) => $a['status'] === 'hired')),
                'applications' => array_values(array_filter($applications, fn($a) => $a['status'] === 'hired')),
            ],
            [
                'status' => 'rejected',
                'label' => 'Rejected',
                'count' => count(array_filter($applications, fn($a) => $a['status'] === 'rejected')),
                'applications' => array_values(array_filter($applications, fn($a) => $a['status'] === 'rejected')),
            ],
        ];

        // Summary statistics
        $summary = [
            'total_candidates' => 45,
            'active_applications' => count(array_filter($applications, fn($a) => !in_array($a['status'], ['hired', 'rejected', 'withdrawn']))),
            'interviews_this_week' => 8,
            'offers_pending' => 2,
            'hires_this_month' => 3,
            'rejection_rate' => round((15 / 45) * 100, 1),
            'avg_time_to_hire' => 21, // days
            'conversion_rate' => round((3 / 45) * 100, 1),
        ];

        // Job postings for filtering
        $jobPostings = [
            ['id' => 1, 'title' => 'Senior Software Engineer', 'open_positions' => 2],
            ['id' => 2, 'title' => 'Marketing Manager', 'open_positions' => 1],
            ['id' => 3, 'title' => 'Financial Analyst', 'open_positions' => 2],
            ['id' => 4, 'title' => 'HR Coordinator', 'open_positions' => 1],
            ['id' => 5, 'title' => 'Customer Service Representative', 'open_positions' => 3],
            ['id' => 6, 'title' => 'Project Manager', 'open_positions' => 1],
            ['id' => 7, 'title' => 'Data Analyst', 'open_positions' => 2],
            ['id' => 8, 'title' => 'Sales Executive', 'open_positions' => 2],
            ['id' => 9, 'title' => 'Operations Manager', 'open_positions' => 1],
        ];

        // Default view mode: kanban or list
        $viewMode = $request->query('view', 'kanban');

        return Inertia::render('HR/ATS/HiringPipeline/Index', [
            'pipeline' => $pipeline,
            'summary' => $summary,
            'jobPostings' => $jobPostings,
            'viewMode' => $viewMode,
            'filters' => [
                'job_posting_id' => $request->query('job_posting_id'),
                'source' => $request->query('source'),
            ],
            'sources' => [
                ['value' => 'referral', 'label' => 'Referral'],
                ['value' => 'job_board', 'label' => 'Job Board'],
                ['value' => 'walk_in', 'label' => 'Walk-in'],
                ['value' => 'agency', 'label' => 'Agency'],
                ['value' => 'internal', 'label' => 'Internal'],
                ['value' => 'facebook', 'label' => 'Facebook'],
                ['value' => 'other', 'label' => 'Other'],
            ],
            'breadcrumbs' => [
                ['label' => 'HR', 'href' => route('hr.dashboard')],
                ['label' => 'ATS', 'href' => route('hr.ats.job-postings.index')],
                ['label' => 'Hiring Pipeline', 'href' => null],
            ],
        ]);
    }

    /**
     * Move application to a different status.
     */
    public function moveApplication(Request $request, $id)
    {
        $validated = $request->validate([
            'status' => 'required|in:submitted,shortlisted,interviewed,offered,hired,rejected,withdrawn',
            'notes' => 'nullable|string',
        ]);

        // Mock response - would normally update database
        return back()->with('success', 'Application moved successfully');
    }
}
